/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, styled, Typography } from "@mui/material";
import { useEffect } from "react";
import { useRouter } from "next/router";
import HomePage from "../feature/HomePage";
import axios from "axios";
import { useRecoilState } from "recoil";
import { userInfomation } from "../store/userState";
export default function Home() {
  const router = useRouter();
  const [userData, setUserData] = useRecoilState(userInfomation);

  const fetchAPI = async (token: any) => {
    const fetchData = await axios({
      method: "POST",
      data: {
        loginType: "FB",
        token: token,
      },
      url: "http://localhost:8081/api/v1/login",
    });
    setUserData(fetchData.data.user);
  };
  useEffect(() => {
    const token = localStorage.getItem("TOKEN");
    if (token == undefined) {
      router.push("/login");
    } else {
      fetchAPI(token);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          type="text/javascript"
          src="//connect.facebook.net/en_US/all.js#xfbml=1&appId=5556830631091437"
          id="facebook-jssdk"
        ></script>
      </Head>
      <>
        <HomePage userInform={userData} />
      </>
    </div>
  );
}
